language: node_js
node_js:
- '0.10'
deploy:
  provider: s3
  access_key_id: AKIAJGGTPSBAMBLGK7EA
  secret_access_key:
    secure: ckdjNymE3a90FB5kXbzan3RVlzH4frnjfQP5W+mzsFdDKGMsrRFOOkRkm7sdvJzOO/NlBEWvdAYUMXFs/aTUzX/InJnnH+wMeLCHovYOw4FUIzMh7Z7gxPI2hWClY+r55fG78ykl+xG4GHT70L7eN3anhqlTY3ZNPtXCZB1YmVU=
  bucket: hoistedjs
  local-dir: dist
  upload-dir: "assets/js"
  acl: public_read
  on:
    repo: MiguelCastillo/spromise
